### ISSUE TITLE
Feature request: please add cyrillic and greek support

### ISSUE THREAD

**Issue by renatlot** [Corne2Plum3/Giphurs#13]
Hope this wonderful font set will have cyrillic and greek support

**Comment by zerorabb** [comment]
It already does!

**Comment by renatlot** [comment]
Super, thank you! Will note fontesk.com they should match all languages supported. 
Waiting for added to Google Fonts!

**Comment by renatlot** [comment]
Super, thank you! Will note fontesk.com they should match all languages supported.
Waiting for added to Google Fonts!
