### ISSUE TITLE
Questionable design of Ф

### ISSUE THREAD

**Issue by ravid-dubsteper** [Corne2Plum3/Giphurs#18]
The current design of the letter Ф is questionable. It has unnecessary serifs and the oval is small.
![image_2024-09-29_03-25-09](https://github.com/user-attachments/assets/8889aac3-ec99-4129-abeb-150df5dc4b13)
I think you should remove the serifs and make the oval bigger and wider, like here:
![image_2024-09-29_03-25-10](https://github.com/user-attachments/assets/60d10f71-3cc8-4dc6-ba50-f37d2b1938e7)

**Comment by Corne2Plum3** [comment]
Tried new design of the letter (`U+0422` and `U+0444`), and also changed the lowercase as it could have been incorrect as well. Is it good?

![Image](https://github.com/user-attachments/assets/71ce592b-1f6a-4743-8bac-0524bbef9075)

**Comment by ravid-dubsteper** [comment]
i think that current lowercase and new uppercase are better together. new lowercase is acceptable, but it is more for display usage. it's okay if u will keep it for stylistic set
![image](https://github.com/user-attachments/assets/ae64ef8e-328b-4163-a1ed-6325f78075cc)

**Comment by Corne2Plum3** [comment]
The new design has been added in version 1.1.0.

https://github.com/Corne2Plum3/Giphurs/releases/tag/v1.1.0
