### ISSUE TITLE
"Y" instead of "У" in SC fonts in lowercase

### ISSUE THREAD

**Issue by Daymarius** [Corne2Plum3/Giphurs#22]
![image](https://github.com/user-attachments/assets/ca93de37-8a73-45d7-8931-f176815a7fec)

**Comment by Corne2Plum3** [comment]
`uni0443.sc` shouldn't look like an 'Y', you're right. I'll fix it.

**Comment by Corne2Plum3** [comment]
Fixed with #23, the fix will be in the next update (I can do a new version right now if you REALLY need a fixed version as soon as possible.)

**Comment by Daymarius** [comment]
> Fixed with #23, the fix will be in the next update (I can do a new version right now if you REALLY need a fixed version as soon as possible.)

I'm in no hurry, I just found a discrepancy and reported it.

**Comment by Corne2Plum3** [comment]
Added in ![version 1.1.1](https://github.com/Corne2Plum3/Giphurs/releases/tag/v1.1.1)
