### ISSUE TITLE
"v" between weights 400-900 interpolated weirdly

### ISSUE THREAD

**Issue by PineappleRind** [Corne2Plum3/Giphurs#3]
gradually inverting itself...lol

<img width="360" alt="Screen Shot 2023-08-06 at 10 03 05 AM" src="https://github.com/Corne2Plum3/Giphurs/assets/65303441/d49dae6c-00fd-4aa2-ac6f-e3d638b86f10">

v0.8.0

**Comment by Corne2Plum3** [comment]
At least this is the only one lol 
![image](https://github.com/Corne2Plum3/Giphurs/assets/57914482/8e7c72da-b96f-43df-ae7b-d15f41f47f7f)

**Comment by Corne2Plum3** [comment]
Fixed in 757ab04610fe6e8c4e15fb2b31c1d6d8a7d99533, it will be for the next release (v0.8.1)
